### ISSUE TITLE
Respond as a bot to pull requests?

### ISSUE THREAD

**Issue by wlandau** [r-releases/r-releases#3]
In https://github.com/r-releases/r-releases/pull/2, for some reason I am the one who is commenting on pull requests, not a bot. Maybe this has something to do with how I set up the temporary fine-grained tokens to get it to work? It would be preferable if those tokens belonged to a service account and not me. Apparently they can't belong to orgs.

**Comment by wlandau** [comment]
I have stopped the automation until we figure out how to use a bot for this.

**Comment by shikokuchuo** [comment]
I think you can do it by creating a Github app.

**Comment by wlandau** [comment]
Yeah, you're right. Seems to be what the docs recommend. I created one called `r-releases-app` and set up the https://github.com/r-releases/r-releases.r-universe.dev/blob/main/.github/workflows/review_pull_requests.yaml action to use it. Hopefully it merges https://github.com/r-releases/r-releases/pull/5.

**Comment by wlandau** [comment]
Looks like the bot works!
